//! Auto-mounted Rizzma figure used by the Performance settings panel.

use gloo::events::EventListener;
use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::JsFuture;
use web_sys::HtmlIFrameElement;
use yew::prelude::*;

#[wasm_bindgen(module = "/rizzma-host.js")]
extern "C" {
    #[wasm_bindgen(js_name = mountRizzmaChart)]
    fn mount_rizzma_chart(
        frame: HtmlIFrameElement,
        artifact_url: &str,
        renderer_version: &str,
    ) -> js_sys::Promise;

    #[wasm_bindgen(js_name = disposeRizzma)]
    fn dispose_rizzma(frame: HtmlIFrameElement);
}

#[derive(Properties, PartialEq)]
pub struct RizzmaChartProps {
    pub title: AttrValue,
    pub artifact_url: AttrValue,
}

/// A static, interactive performance figure. The artifact is generated by the
/// authenticated backend and executed only through Portal's pinned Rizzma
/// 1.12 runtime in an opaque-origin sandbox.
#[function_component(RizzmaChart)]
pub fn rizzma_chart(props: &RizzmaChartProps) -> Html {
    let frame_ref = use_node_ref();
    let loading = use_state(|| true);
    let error = use_state(|| None::<String>);

    {
        let frame_ref = frame_ref.clone();
        let url = props.artifact_url.clone();
        let loading = loading.clone();
        let error = error.clone();
        use_effect_with(url, move |url| {
            let Some(frame) = frame_ref.cast::<HtmlIFrameElement>() else {
                error.set(Some("Rizzma chart frame is unavailable".to_string()));
                loading.set(false);
                return Box::new(|| {}) as Box<dyn FnOnce()>;
            };
            loading.set(true);
            error.set(None);
            let promise = mount_rizzma_chart(frame.clone(), url, "1.12.0");
            let loading_task = loading.clone();
            let error_task = error.clone();
            wasm_bindgen_futures::spawn_local(async move {
                if let Err(value) = JsFuture::from(promise).await {
                    error_task.set(Some(
                        value
                            .as_string()
                            .unwrap_or_else(|| "Rizzma chart failed to mount".to_string()),
                    ));
                }
                loading_task.set(false);
            });
            // Keep a listener alive for the realm's state events. Static charts
            // do not consume them, but registering it makes future interactive
            // controls additive without changing the host lifecycle.
            let listener = EventListener::new(&frame, "rizzma-state", |_| {});
            Box::new(move || {
                drop(listener);
                dispose_rizzma(frame);
            }) as Box<dyn FnOnce()>
        });
    }

    html! {
        <div class="performance-chart performance-rizzma-chart">
            <h3 class="chart-title">{ props.title.clone() }</h3>
            <div class="performance-rizzma-viewport">
                <iframe
                    ref={frame_ref}
                    class="performance-rizzma-frame"
                    sandbox="allow-scripts"
                    title={props.title.clone()}
                />
                if *loading {
                    <div class="performance-rizzma-status">{ "Rendering…" }</div>
                }
                if let Some(message) = &*error {
                    <div class="performance-rizzma-status error">{ message }</div>
                }
            </div>
        </div>
    }
}
